# 8.30  stats
mean is given by $\frac{\sum_{n=1}^{N} x_n }{N}$

We need to take a limit as N ->$\inf$ to get the probability, $p$

for a coin flip $x_n \in \{0,1\}$, and the $p \in \{0,1\}$



In [1]:
import numpy as np
import bplot as bp
import matplotlib.pyplot as plt

In [2]:
N = 5
x = np.random.choice([0,1], N)
x.mean()

0.4

In [3]:
N = 500
x = np.random.choice([0,1], N)
x.mean()

0.466

Because stats only works in the limit of large numbers you can get into trouble because some sciences are very expensive. You can't always get another observation, let alone 50000000 more 

# learning a new package and indexing

In [4]:
c = np.cumsum(x)

In [5]:
x[:6]

array([0, 0, 1, 0, 1, 0])

In [6]:
c[:6]

array([0, 0, 1, 1, 2, 2])

In [7]:
#p[-1] #prints last value. When going from end arrays are 1 indexed. Annoying python thing

In [8]:
#p[10:15] #array slicing

In [9]:
np.arange(10) #note, inclusive 0, exclusive 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10) + 1 # elementwise addition

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Vectorization: when a language drops down to it's base language to do some iteration. 

# back to stats

In [11]:
p = c / (np.arange(N) + 1)

In [12]:
print(p[10])

0.36363636363636365


In [13]:
bp.line(np.arange(N), p)

Now change from coin flip to roll of a die, ie: $x \in \{ 1,2,3,4,5,6\}$


In [14]:
N = 500
x = np.random.choice([1,2,3,4,5,6], N)
x.mean()

3.696

In [15]:
p = c / (np.arange(N) + 1)

In [16]:
bp.line(np.arange(N), p)

The probability you aproach is called $\mu$. It exists but you can't always know it

sample: can be a noun or a verb

    (v) take a sample from a group

    (n) you can have a sample of things

population: the group of things with which you are inerseted in learning about 

parameters: characteristics of the population 

on the sample side, you estimate population paramaters. 

Statistics: any function of the sample that estimates some value that is determined in the limit as N -> $\infinity$

    examples: mean, median, mode, std dev, etc