# Basic Mathematical Operations Using Arrays

In [2]:
import numpy as np
import timeit

x = np.array([[ 0.,  1.,  2.],
               [ 3.,  4.,  5.],
               [ 6.,  7.,  8.]])

y = np.array([[-4. , -3.5, -3. ],
               [-2.5, -2. , -1.5],
               [-1. , -0.5, -0. ]])

In [3]:
#elemant wise opperation

x ** 2

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]])

In [4]:
#element wise between arays too!

x + y

array([[-4. , -2.5, -1. ],
       [ 0.5,  2. ,  3.5],
       [ 5. ,  6.5,  8. ]])

In [5]:
# Slices return arrays, thus you can operate
# on these too.
.5 + x[0, :]

array([0.5, 1.5, 2.5])

In [6]:
np.sum(x)

36.0

In [7]:
np.sum(x, axis = 0)

array([ 9., 12., 15.])

 # Vectorized Operations
 
NumPy’s ND-arrays are homogeneous: an array can only contain data of a single type.
Knowing that an array’s contents are homogeneous, NumPy can do math in C very quickly.

In [8]:
#time test for vectorization vs for loop
N = 10001
x = np.random.normal(size = N)
setup = "import numpy as np"



sumtime = timeit.timeit(setup = setup, 
                    stmt = "np.sum(x)", 
                    number = 1000)/1000 

sumloop = """
arr = x
s = 0
for i in range(N):
    s += arr[i]    
"""

looptime = timeit.timeit(setup = setup,
                        stmt = sumloop,
                        number = 1000)/1000

print("simetime = ", sumtime, "sec")
print("looptime = ", looptime, "sec")
print("looptime/sumtime = ", looptime/sumtime)


NameError: name 'x' is not defined

In [9]:
#time test for vectorization vs for loop
N = 10001
x = np.random.normal(size = N)

In [10]:
%%timeit

arr = x
s = 0
for i in range(N):
    s += arr[i] 

3.64 ms ± 197 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
#test, erase when block above is fixed

arr = np.arange(10000)
s = 0
for i in range(10000):
    s += arr[i]
    
print(s)

49995000


# Binary Functions
Applying a binary NumPy-function, 𝑓(𝑥,𝑦), to two same-shape arrays will apply 𝑓(𝑥,𝑦) to each of their pairwise elements, producing an array of the same shape as either of the operands.

In [40]:
# example of a binary function operating on two 2D arrays
x = np.array([[10,  2],
              [ 3,  5]])

y = np.array([[ 1,   0],
               [ -4,  -1]])

In [41]:
#adds element wise 
np.add(x, y)

array([[11,  2],
       [-1,  4]])

In [42]:
# add column-0 of `x` and row-1 of `y`
x[:, 0] + y[1, :]

array([6, 2])

In [ ]:
#example: given 
x = np.array([[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11],
               [12, 13, 14, 15]])

#Add the four quadrants of x, producing a shape-(2, 2) output.

x[0:2,0] + x[]